"""D3's sequential half -- anytime-valid monitoring on the signed receipt stream.

The statistics here are **not ours** and the module says so. Conformal test martingales
are Vovk's; weighted conformal monitoring with covariate/concept diagnosis is WATCH
(arXiv:2505.04608, ICML 2025). We adopt them rather than compete.

What *is* ours is what the crossing acts on. The monitored object is a
cryptographically signed, non-repudiable provenance stream, so a crossing is not a
dashboard alarm -- it is a **state transition of a signed assessment record** that
revokes a named authority's risk acceptance. An alarm can be argued away as
instrumentation error; a hash-chained receipt stream cannot.

**The obvious null is false and we do not use it.** Exchangeability of the receipt
stream fails for any fielded system: a camera on a border post sees seasons, weather
and changed tasking. An unweighted conformal test martingale fires on drift alone --
arXiv:2608.30502 reports **135 of 135 clean-stream runs firing at alpha = 0.05** on
real forecast streams. So the null is *weighted* exchangeability, the weight model and
the bag-sufficiency assumption are declared in the report, and where the weight model
cannot be fitted the monitor emits ``no_weight_model`` and falls back to a dated
re-assessment interval.

The product appears here and only here: the factors are sequentially constructed, so
each is measurable with respect to the filtration generated by the past and the product
is a genuine e-process. Everywhere else in this codebase e-values are averaged.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from pramana.common.errors import AssessmentUnavailable
from pramana.ledger.chain import HashChain

__all__ = ["EProcess", "EpochCandidates", "MonitorResult"]

#: D4.a -- the candidate change points are exogenous, signed supply-chain acts, not
#: every index. That is not a trick to shrink the mixture penalty: every candidate is a
#: ledger row written BEFORE the data it precedes, and the signature is what makes that
#: checkable rather than asserted. When a crossing lands on no signalled act we do not
#: manufacture one -- the report says `unexplained_epoch`, which is strictly worse for
#: us, because it is an alarm we cannot attribute to anybody.
EPOCH_EVENTS = (
    "lot_admitted",
    "converter_version_change",
    "calibration_set_change",
    "contract_relet",
    "disposition_set",
)


@dataclass
class EpochCandidates:
    """Signed contract events that may start a monitoring epoch."""

    indices: list[int] = field(default_factory=list)
    signers: list[str] = field(default_factory=list)
    event_types: list[str] = field(default_factory=list)

    @classmethod
    def from_ledger(cls, chain: HashChain, receipt_index_of: dict[str, int]) -> EpochCandidates:
        """Build the candidate set from signed ledger rows.

        ``receipt_index_of`` maps a ledger ``entry_hash`` to the receipt-stream index
        at which that act took effect. The mapping is fixed by the same pre-commitment
        that pins the probe battery, so the candidate set cannot grow after an alarm.
        """
        idx, sgn, ev = [], [], []
        for entry in chain.events_of(*EPOCH_EVENTS):
            pos = receipt_index_of.get(entry.entry_hash)
            if pos is not None:
                idx.append(pos)
                sgn.append(entry.signer_id)
                ev.append(entry.event_type)
        return cls(indices=idx, signers=sgn, event_types=ev)

    def attribute(self, crossing_index: int) -> dict[str, object]:
        """Name the signer whose act preceded a crossing, or admit we cannot."""
        prior = [(i, s, e) for i, s, e in zip(self.indices, self.signers, self.event_types) if i <= crossing_index]
        if not prior:
            return {
                "epoch_attributed": False,
                "reason": "unexplained_epoch",
                "note": (
                    "The crossing does not follow any signalled supply-chain act. We do "
                    "not manufacture one."
                ),
            }
        i, signer, event = max(prior, key=lambda t: t[0])
        return {
            "epoch_attributed": True,
            "epoch_start_index": i,
            "epoch_event": event,
            "epoch_signer": signer,
            "receipts_since_epoch": crossing_index - i,
        }


@dataclass
class MonitorResult:
    crossed: bool
    crossing_index: int | None
    max_e: float
    threshold: float
    trace: np.ndarray
    attribution: dict[str, object] = field(default_factory=dict)
    false_alarms: int = 0

    def as_dict(self) -> dict[str, object]:
        return {
            "crossed": self.crossed,
            "crossing_index": self.crossing_index,
            "max_e_value": round(self.max_e, 4),
            "threshold": self.threshold,
            "threshold_basis": "1/alpha; Ville's inequality bounds the type-I rate at alpha",
            "n_receipts": int(self.trace.size),
            **self.attribution,
        }


class EProcess:
    """A conformal test martingale over receipt-derived conformal p-values.

    **The calibrator is the whole correctness argument.** A first implementation used
    the per-step factor ``e = 1/p``. That is invalid and it fails loudly: under the
    null ``p`` is uniform on (0, 1) and ``E[1/p]`` diverges, so the product grows
    without bound on a perfectly clean stream. In testing it crossed at receipt 3 of a
    6,000-receipt clean prefix -- the 135-of-135 false-alarm result of
    arXiv:2608.30502 reproduced in miniature, by our own bug.

    A valid calibrator must satisfy ``E[factor] <= 1`` under the null. Two are
    implemented and the default needs no tuning parameter:

    * **power** -- ``f(p) = eps * p**(eps-1)`` for ``eps`` in (0, 1). Exactly a
      martingale: ``integral_0^1 eps * p**(eps-1) dp = 1``. Powerful against a
      specific alternative, and you have to pick ``eps``.
    * **mixture** (default) -- Vovk's simple mixture, integrating the power martingale
      over ``eps`` in (0, 1). No parameter to choose and no alternative to guess,
      which is what you want when the change you are watching for is a backdoor
      activating at an unknown amplitude.

    ``weights`` belongs to the *p-value computation* upstream, not here: WATCH-style
    weighted conformal prediction produces weighted p-values and this class consumes
    them. The parameter is retained only so the monitor can **refuse** when no weight
    model exists, because an unweighted martingale on a dependent fielded stream is
    exactly the configuration that cries wolf and gets switched off in week two.
    """

    def __init__(
        self,
        alpha: float = 0.05,
        weights: np.ndarray | None = None,
        *,
        calibrator: str = "mixture",
        epsilon: float = 0.5,
        grid_size: int = 100,
    ):
        if calibrator not in ("mixture", "power"):
            raise ValueError(f"unknown calibrator {calibrator!r}")
        self.alpha = alpha
        self.threshold = 1.0 / alpha
        self.weights = weights
        self.calibrator = calibrator
        self.epsilon = epsilon
        #: Midpoint grid over (0, 1); avoids the endpoints where the power martingale
        #: degenerates to the trivial and the undefined case respectively.
        self._grid = (np.arange(grid_size) + 0.5) / grid_size
        self._log_m = np.zeros(grid_size)
        self._log_e = 0.0
        self._trace: list[float] = []

    @property
    def threshold_basis(self) -> str:
        return "1/alpha; Ville's inequality bounds the type-I error at alpha at ANY stopping time"

    @property
    def calibrator_basis(self) -> str:
        if self.calibrator == "power":
            return f"power martingale, eps={self.epsilon}: E[eps*p^(eps-1)] = 1 under uniform p"
        return "Vovk simple mixture: power martingale integrated over eps in (0,1)"

    def reset(self) -> None:
        self._log_m = np.zeros_like(self._grid)
        self._log_e = 0.0
        self._trace = []

    def update(self, p_value: float) -> float:
        """Feed one conformal p-value and return the running martingale value."""
        p = float(np.clip(p_value, 1e-12, 1.0))
        log_p = np.log(p)

        if self.calibrator == "power":
            eps = self.epsilon
            self._log_e += np.log(eps) + (eps - 1.0) * log_p
            m = float(np.exp(np.clip(self._log_e, -700.0, 700.0)))
        else:
            self._log_m += np.log(self._grid) + (self._grid - 1.0) * log_p
            # log-sum-exp mean over the grid, for numerical stability
            peak = float(self._log_m.max())
            m = float(np.exp(min(peak, 700.0)) * np.mean(np.exp(np.clip(self._log_m - peak, -700.0, 0.0))))

        self._trace.append(m)
        return m

    def run(
        self,
        p_values: np.ndarray,
        *,
        candidates: EpochCandidates | None = None,
        require_weight_model: bool = True,
    ) -> MonitorResult:
        """Run the monitor over a receipt stream.

        Raises :class:`AssessmentUnavailable` with ``no_weight_model`` when weighting is
        required and unavailable -- because an unweighted martingale on a dependent
        deployment stream is the configuration that fired on 135 of 135 clean runs.
        """
        if require_weight_model and self.weights is None:
            raise AssessmentUnavailable(
                "no_weight_model",
                "Exchangeability fails on a fielded stream; without a weight model the "
                "monitor would fire on seasonal drift alone. Falling back to a dated "
                "re-assessment interval.",
            )

        self.reset()
        crossing = None
        for i, p in enumerate(np.asarray(p_values, dtype=float).ravel()):
            m = self.update(p)
            if crossing is None and m >= self.threshold:
                crossing = i

        trace = np.asarray(self._trace, dtype=float)
        attribution = candidates.attribute(crossing) if (candidates and crossing is not None) else {}

        return MonitorResult(
            crossed=crossing is not None,
            crossing_index=crossing,
            max_e=float(trace.max()) if trace.size else 0.0,
            threshold=self.threshold,
            trace=trace,
            attribution=attribution,
        )


def false_alarm_count(clean_streams: list[np.ndarray], alpha: float = 0.05) -> int:
    """Count crossings on streams known to be clean.

    E6's pass condition is **false-alarms-first**: at most one false alarm across the
    whole dependent drift replay *before* any detection credit is claimed. Testing
    detection before the false-alarm rate on drift we can actually generate is how a
    monitor like this gets shipped and then switched off in week two.
    """
    alarms = 0
    for stream in clean_streams:
        proc = EProcess(alpha=alpha, weights=np.ones(len(stream)))
        if proc.run(stream, require_weight_model=False).crossed:
            alarms += 1
    return alarms
