"""D3 -- contributor-denominated evidence aggregation.

Clause 2.2.1 demands that sample-level evidence roll up to a **source-level** risk
assessment rather than flagging samples in isolation. This module is that roll-up, and
the operator it uses is the whole point.

**E-values are merged by averaging, not by multiplication.**

The first draft had the operator backwards, and it was a statistical error rather than
a wording problem. The product of e-values is valid only when the factors are
independent, or when they are constructed sequentially so each is measurable with
respect to the filtration generated by the past. Under *arbitrary* dependence the valid
merge is the arithmetic mean (Vovk & Wang, arXiv:1912.06116, Ann. Statist. 49(3)). The
arithmetic is one line: for weights w summing to 1, E[sum w_i E_i] = sum w_i E[E_i] <= 1
whatever the dependence. Four detectors on the same shard are emphatically not
independent.

Averaging is also the **more powerful** choice against the attack the clause names.
Poisoning by one supplier is sparse: a fraction alpha of that source's samples carry
large evidence E, the rest carry about 1. The mean gives roughly alpha*E; the geometric
mean gives roughly E^alpha. For E = 100 and alpha = 0.1 that is 10 versus 1.58.

Three levels, each naming its own justification -- see :data:`MERGE_RULES`.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from pramana.common import constants as K

__all__ = [
    "SourceEvidence",
    "merge_within_detector",
    "merge_across_detectors",
    "ebh_threshold",
    "ebh_reject",
    "aggregate_sources",
]

#: Documented so that a reader can check the operator against its justification
#: without reading the code. The third row is the ONLY place a product is valid.
MERGE_RULES = {
    "within_detector": (
        "arithmetic_mean_size_normalised",
        "Arbitrary dependence within a shard; Vovk-Wang averaging.",
    ),
    "across_detectors": (
        "weighted_arithmetic_mean",
        "Same result; weights fixed in the battery manifest before the artefact arrives.",
    ),
    "along_receipt_stream": (
        "product",
        "Valid here and only here: the factors are sequentially constructed, so the "
        "product is a genuine e-process.",
    ),
}


def merge_within_detector(e_values: np.ndarray, *, size_normalise: bool = True) -> float:
    """Merge per-sample e-values for one detector on one source.

    ``size_normalise`` divides by the shard size, which is what stops a large lot
    accumulating evidence simply by being large. Without it, the biggest supplier is
    always the most suspicious, which is the opposite of useful.
    """
    e = np.asarray(e_values, dtype=float).ravel()
    if e.size == 0:
        return 1.0
    if np.any(e < 0):
        raise ValueError("e-values cannot be negative.")
    return float(e.mean()) if size_normalise else float(e.sum())


def merge_across_detectors(
    per_detector: dict[str, float],
    weights: dict[str, float] | None = None,
) -> tuple[float, dict[str, float]]:
    """Merge one source's per-detector e-values by **weighted arithmetic mean**.

    Weights must be pre-committed in the battery manifest and sum to 1, so they cannot
    be tuned after the artefact is seen. That is a G1 property, not a statistical one,
    and it is why the weights digest travels in the report.
    """
    if not per_detector:
        return 1.0, {}
    if weights is None:
        w = {k: 1.0 / len(per_detector) for k in per_detector}
    else:
        missing = set(per_detector) - set(weights)
        if missing:
            raise ValueError(f"no pre-committed weight for detector(s) {sorted(missing)}")
        w = {k: weights[k] for k in per_detector}
        total = sum(w.values())
        if abs(total - 1.0) > 1e-9:
            raise ValueError(
                f"merge weights sum to {total}, not 1. A weighted mean whose weights do "
                f"not sum to one is not a valid e-value merge."
            )
    merged = sum(w[k] * v for k, v in per_detector.items())
    return float(merged), w


def ebh_threshold(m: int, k: int = 1, fdr: float = K.DECLARED_FDR) -> float:
    """e-BH rejection threshold: ``m / (alpha * k)``.

    The multiplicity is the number of **contributors**, which is small and known --
    that is what makes "source-07 is flagged" a statement with a stated error rate
    rather than a ranking.
    """
    if m < 1 or k < 1:
        raise ValueError("m and k must be >= 1")
    return m / (fdr * k)


def ebh_reject(e_values: dict[str, float], *, fdr: float = K.DECLARED_FDR) -> dict[str, object]:
    """Apply e-BH across the supplier list at a declared false-discovery rate.

    Returns the rejected sources, the threshold they cleared, and the full sorted list
    -- because a source that merged to 41.6 against a threshold of 240 is information
    the report should carry, not hide.
    """
    m = len(e_values)
    if m == 0:
        return {"rejections": [], "threshold_at_k1": None, "sources_tested": 0, "fdr": fdr}

    ordered = sorted(e_values.items(), key=lambda kv: kv[1], reverse=True)
    rejected: list[str] = []
    for k in range(len(ordered), 0, -1):
        thr = ebh_threshold(m, k, fdr)
        if ordered[k - 1][1] >= thr:
            rejected = [src for src, _ in ordered[:k]]
            break

    return {
        "rejections": rejected,
        "threshold_at_k1": ebh_threshold(m, 1, fdr),
        "sources_tested": m,
        "fdr": fdr,
        "ranked": [{"source": s, "e_value": round(v, 4)} for s, v in ordered],
    }


@dataclass
class SourceEvidence:
    """One contributor's aggregated evidence, with everything the report needs."""

    source_id: str
    per_detector: dict[str, float] = field(default_factory=dict)
    merged: float = 1.0
    weights: dict[str, float] = field(default_factory=dict)
    n_samples: int = 0
    rejected: bool = False
    threshold: float | None = None

    def as_statistic(self, *, sources_tested: int, weights_digest: str) -> dict[str, object]:
        return {
            "name": "e_value_merged",
            "value": round(self.merged, 4),
            "merging_function": "weighted_arithmetic_mean",
            "merge_weights_committed_in": weights_digest,
            "within_detector_merge": MERGE_RULES["within_detector"][0],
            "fdr": K.DECLARED_FDR,
            "sources_tested": sources_tested,
            "size_normalised": True,
            "ebh_threshold_at_k1": self.threshold,
            "ebh_rejections": int(self.rejected),
            "note": (
                f"e-BH rejects source i when e_i >= m/(alpha*k) = {sources_tested}/"
                f"({K.DECLARED_FDR}*1) = {self.threshold}. "
                + ("Rejected at declared FDR." if self.rejected else "NOT reported as a finding.")
            ),
        }


def aggregate_sources(
    per_source_detector_evalues: dict[str, dict[str, np.ndarray]],
    *,
    weights: dict[str, float] | None = None,
    weights_digest: str = "battery_manifest@unknown",
    fdr: float = K.DECLARED_FDR,
) -> tuple[list[SourceEvidence], dict[str, object]]:
    """Full three-level aggregation: samples -> detector -> source -> FDR over sources.

    Returns every source's evidence (including the ones not flagged) and the e-BH
    decision block. Nothing is dropped: a source list that shows only the accused is
    a list nobody can calibrate against.
    """
    evidences: list[SourceEvidence] = []
    for source_id, detectors in per_source_detector_evalues.items():
        per_detector = {
            name: merge_within_detector(values) for name, values in detectors.items()
        }
        merged, used_weights = merge_across_detectors(per_detector, weights)
        n = max((np.asarray(v).size for v in detectors.values()), default=0)
        evidences.append(
            SourceEvidence(
                source_id=source_id,
                per_detector=per_detector,
                merged=merged,
                weights=used_weights,
                n_samples=n,
            )
        )

    decision = ebh_reject({e.source_id: e.merged for e in evidences}, fdr=fdr)
    rejected = set(decision["rejections"])  # type: ignore[arg-type]
    for e in evidences:
        e.rejected = e.source_id in rejected
        e.threshold = decision["threshold_at_k1"]  # type: ignore[assignment]

    evidences.sort(key=lambda e: e.merged, reverse=True)
    return evidences, decision
